# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'testservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11testservice.proto\x12\x0btestservice\"0\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65lay_ms\x18\x02 \x01(\x05\"7\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x16\n\x0erequest_number\x18\x02 \x01(\x05\"o\n\x11StreamEchoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x1c\n\x14\x66irst_chunk_delay_ms\x18\x03 \x01(\x05\x12\x1c\n\x14inter_chunk_delay_ms\x18\x04 \x01(\x05\":\n\x12StreamEchoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x32\x9b\x01\n\x0bTestService\x12;\n\x04\x45\x63ho\x12\x18.testservice.EchoRequest\x1a\x19.testservice.EchoResponse\x12O\n\nStreamEcho\x12\x1e.testservice.StreamEchoRequest\x1a\x1f.testservice.StreamEchoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=34
  _globals['_ECHOREQUEST']._serialized_end=82
  _globals['_ECHORESPONSE']._serialized_start=84
  _globals['_ECHORESPONSE']._serialized_end=139
  _globals['_STREAMECHOREQUEST']._serialized_start=141
  _globals['_STREAMECHOREQUEST']._serialized_end=252
  _globals['_STREAMECHORESPONSE']._serialized_start=254
  _globals['_STREAMECHORESPONSE']._serialized_end=312
  _globals['_TESTSERVICE']._serialized_start=315
  _globals['_TESTSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
